# Generated by Django 4.2.7 on 2026-01-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='construction_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='总建筑面积', max_digits=12, verbose_name='建筑面积(㎡)'),
        ),
        migrations.AddField(
            model_name='project',
            name='greening_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='绿化率(%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='plot_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='容积率'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_floors',
            field=models.IntegerField(default=0, verbose_name='总楼层数'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_rooms',
            field=models.IntegerField(default=0, verbose_name='总房号数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_units',
            field=models.IntegerField(default=0, verbose_name='总单元数'),
        ),
    ]
