# Generated by Django 4.2.7 on 2026-01-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_construction_area_project_greening_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='greening_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='plot_ratio',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_floors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_rooms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_units',
        ),
        migrations.AddField(
            model_name='project',
            name='floors_per_unit',
            field=models.IntegerField(default=20, verbose_name='每单元楼层数'),
        ),
        migrations.AddField(
            model_name='project',
            name='units_per_building',
            field=models.IntegerField(default=2, verbose_name='每楼栋单元数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='总建筑面积', max_digits=12, verbose_name='建筑面积(㎡)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_buildings',
            field=models.IntegerField(default=1, verbose_name='总楼栋数'),
        ),
    ]
