# Generated by Django 4.2.7 on 2026-01-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_greening_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rooms_per_floor',
            field=models.IntegerField(default=4, verbose_name='每楼层房号数'),
        ),
    ]
