# Generated by Django 4.2.7 on 2025-12-24 16:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(max_length=50, verbose_name='楼栋号')),
                ('unit_number', models.CharField(max_length=50, verbose_name='单元号')),
                ('room_number', models.CharField(max_length=50, verbose_name='房号')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('building_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='建筑面积(㎡)')),
                ('interior_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='套内面积(㎡)')),
                ('shared_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='公摊面积(㎡)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价(元/㎡)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总价(元)')),
                ('location_description', models.TextField(blank=True, verbose_name='位置描述')),
                ('status', models.CharField(choices=[('available', '可售'), ('reserved', '已预订'), ('sold', '已售'), ('unavailable', '不可售')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '房源',
                'verbose_name_plural': '房源',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'building_number', 'unit_number', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价(元/㎡)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总价(元)')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='调价原因')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='properties.property', verbose_name='房源')),
            ],
            options={
                'verbose_name': '价格历史',
                'verbose_name_plural': '价格历史',
                'ordering': ['-changed_at'],
            },
        ),
    ]
