# Generated by Django 4.2.7 on 2026-01-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_purchased',
            field=models.BooleanField(default=False, verbose_name='已购房'),
        ),
    ]
