# Generated by Django 4.2.7 on 2025-12-24 16:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成交价(元)')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='首付款(元)')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='付款方式')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='合同编号')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='签约日期')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.customer', verbose_name='客户')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='properties.property', verbose_name='房源')),
                ('salesperson', models.ForeignKey(limit_choices_to={'role': 'salesperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='业务员')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
